config/routes.rb
Rails.application.routes.draw do
  # get 'pages/index'
  # get 'pages/show'
  # get 'pages/new'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :pages
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/page.rb
class Page < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    puts "in index method yo"
    @pages = Page.all 

    # although we don;t rails automatically does this for us 
    #rails is going to look for index.html.erb in the views/pages folder
  end

  def show
    @page = Page.find(params[:id])
  end

  def new
    @page = Page.new
    # go to a folder views/pages/new.html
  end

  def edit
    @page = Page.find(params[:id])
  end

  def update
    @page = Page.find(params[:id])
    if(@page.update(pages_params))
      redirect_to pages_params
    else
      render :edit
    end
  end

  def destroy
    @pages = Page.find(params[:id])
    @page.destroy
    redirect_to pages_path
  end

  def destroy
    Page.find(params[:id]).destroy
    redirect_to pages_path
  end

  def create
    @page = Page.new(pages_params)
    if @page.save
      redirect_to pages_path
    else
      render :new
    end
  end

  private

  def pages_params
    params.require(:page).permit(:subject, :author, :note)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PostIts</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/edit.html.erb
<h1>Edit Page</h1>
<%= form_for @page do |f| %>
  <%= f.label :subject %>
  <%= f.text_field :subject %>
  <%= f.label :author %>
  <%= f.text_field :author %>
  <%= f.label :note %>
  <%= f.text_area :note %>
  <%= f.submit %>
<% end %>

app/views/pages/index.html.erb
<h1>Post-It Notes</h1>
<%= link_to "New Note", new_page_path%>
<% @pages.each do |page| %>
  <h2><%= page.subject%></h2>
  <%# <a href='/'> %>
  <%= link_to 'Show Note', page_path(page)%>
  <%= link_to 'Edit Note', edit_page_path(page)%>
  <%= link_to 'Delete Note', page, method: :delete %>

  <%# <a href="/pages/1">Show Page</a> %>
<% end %>

app/views/pages/new.html.erb
<h1>Create New Note</h1>
<%= form_for @page do |f| %>
  <%= f.label :subject %>
  <%= f.text_field :subject %>
  <%= f.label :author %>
  <%= f.text_field :author %>
  <%= f.label :note %>
  <%= f.text_area :note %>
  <%= f.submit %>
<% end %>

app/views/pages/show.html.erb
<h1><%= @page.subject %></h1>
<h4><%= @page.author %><h4>
<p><%= @page.note %><p>
<%= link_to 'Back', pages_path%>